{"name": "Получение ошибки по не существующему номеру трека", "status": "passed", "description": "Получение ошибки по существующему номеру трека в запросе", "steps": [{"name": "Получение заказа по номеру", "status": "passed", "parameters": [{"name": "t", "value": "'999999999'"}], "start": 1712531653919, "stop": 1712531654022}], "start": 1712531653919, "stop": 1712531654022, "uuid": "9091dcf9-0f7f-4b14-8e00-8231e96654bc", "historyId": "ea8ac6b5a123ea33cf39caeb9d6e9544", "testCaseId": "ea8ac6b5a123ea33cf39caeb9d6e9544", "fullName": "tests.test_order.test_get_order_by_number.TestGetOrderByNumber#test_get_order_by_nonexistent_number", "labels": [{"name": "parentSuite", "value": "tests.test_order"}, {"name": "suite", "value": "test_get_order_by_number"}, {"name": "subSuite", "value": "TestGetOrderByNumber"}, {"name": "host", "value": "WIN-081B0PRJBJT"}, {"name": "thread", "value": "828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order.test_get_order_by_number"}]}